// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smgrckdcmndrxeuzdrsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtZ3Jja2RjbW5kcnhldXpkcnNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDYwMjYsImV4cCI6MjA2MTQyMjAyNn0.F9Lj3AEh_fD_JTiKjMXSJLJtTB32t9N6-6iLzOUHCps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);